# Minimal Initramfs Plugin Example
#
# This is the simplest possible initramfs plugin configuration.
# It creates a bootable initramfs with only busybox and the kestrel agent.
#
# Perfect for: Testing, learning, or as a starting point for custom plugins

version = "1"
strategy = "initramfs"

[agent]
source_strategy = "release"
version = "latest"

[source]
busybox_url = "https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox"
busybox_sha256 = "6e123e7f3202a8c1e9b1f94d8941580a25135382b99e8d3e34fb858bba311348"
