# Runtime Defaults for Go Web Server
#
# This manifest defines the default runtime behavior for the Go web server.
# These defaults can be overridden at VM creation time with volar flags.

schema_version = "v1"
name = "go-webserver"
version = "1.0.0"
runtime = "go-webserver"

[resources]
cpu_cores = 2
memory_mb = 256

[workload]
entrypoint = "/usr/bin/webserver"
args = ["--config", "/etc/webserver/config.yaml"]

[env]
PORT = "8080"
LOG_LEVEL = "info"

[network]
mode = "bridged"

[[network.expose]]
port = 8080
protocol = "tcp"
