# Initramfs Plugin with Go Web Server
#
# This example shows how to package a Go web application as an initramfs plugin.
# 
# Project structure:
#   my-webserver/
#   ├── fledge.toml (this file)
#   └── payload/
#       ├── webserver        (static Go binary)
#       └── config.yaml      (application config)
#
# Build your Go app with: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o payload/webserver

version = "1"
strategy = "initramfs"

[agent]
source_strategy = "release"
version = "latest"

[source]
busybox_url = "https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox"
busybox_sha256 = "6e123e7f3202a8c1e9b1f94d8941580a25135382b99e8d3e34fb858bba311348"

[mappings]
# Map your application binary
"payload/webserver" = "/usr/bin/webserver"

# Map your configuration files
"payload/config.yaml" = "/etc/webserver/config.yaml"
