# Mode 1: Default (Batteries-Included)
# For 90% of users who just want it to work
# C init → Kestrel → Your app

version = "1"
strategy = "initramfs"

[agent]
source_strategy = "release"
version = "latest"

[source]
busybox_url = "https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox"
busybox_sha256 = "6e123e7f3202a8c1e9b1f94d8941580a25135382b99e8d3e34fb858bba311348"

[mappings]
"./caddy" = "/usr/local/bin/caddy"
