# Mode 3: No Init Wrapper
# For the ultimate lazy genius with battle-tested supervisor
# Your binary becomes PID 1 directly

version = "1"
strategy = "initramfs"

[init]
none = true

[source]
busybox_url = "https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox"
busybox_sha256 = "6e123e7f3202a8c1e9b1f94d8941580a25135382b99e8d3e34fb858bba311348"

[mappings]
"./target/x86_64-unknown-linux-musl/release/my-supervisor" = "/init"
